//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace databases
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ИдСв
    {

        private СвИПТип[] свИПField;

        private ИдСвСвЮЛУч[] свЮЛУчField;

        private ИдСвСвЮлНеУч[] свЮлНеУчField;

        private ИдСвСвИнНеУч[] свИнНеУчField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвИП", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СвИПТип[] СвИП
        {
            get
            {
                return this.свИПField;
            }
            set
            {
                this.свИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвЮЛУч", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ИдСвСвЮЛУч[] СвЮЛУч
        {
            get
            {
                return this.свЮЛУчField;
            }
            set
            {
                this.свЮЛУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвЮлНеУч", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ИдСвСвЮлНеУч[] СвЮлНеУч
        {
            get
            {
                return this.свЮлНеУчField;
            }
            set
            {
                this.свЮлНеУчField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвИнНеУч", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ИдСвСвИнНеУч[] СвИнНеУч
        {
            get
            {
                return this.свИнНеУчField;
            }
            set
            {
                this.свИнНеУчField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвИПТип
    {

        private ФИОТип[] фИОField;

        private string иННФЛField;

        private string свГосРегИПField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвГосРегИП
        {
            get
            {
                return this.свГосРегИПField;
            }
            set
            {
                this.свГосРегИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ФИО", Namespace = "", IsNullable = false)]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумНДСТип
    {

        private decimal сумНалField;

        private string безНДСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal СумНал
        {
            get
            {
                return this.сумНалField;
            }
            set
            {
                this.сумНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БезНДС
        {
            get
            {
                return this.безНДСField;
            }
            set
            {
                this.безНДСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумАкцизТип
    {

        private decimal сумАкцизField;

        private string безАкцизField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal СумАкциз
        {
            get
            {
                return this.сумАкцизField;
            }
            set
            {
                this.сумАкцизField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string БезАкциз
        {
            get
            {
                return this.безАкцизField;
            }
            set
            {
                this.безАкцизField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class УчастникТип
    {

        private ИдСв[] идСвField;

        private АдресТип[] адресField;

        private КонтактТип[] контактField;

        private БанкРекв[] банкРеквField;

        private string оКПОField;

        private string структПодрField;

        private string инфДляУчастField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИдСв")]
        public ИдСв[] ИдСв
        {
            get
            {
                return this.идСвField;
            }
            set
            {
                this.идСвField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Адрес")]
        public АдресТип[] Адрес
        {
            get
            {
                return this.адресField;
            }
            set
            {
                this.адресField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Контакт")]
        public КонтактТип[] Контакт
        {
            get
            {
                return this.контактField;
            }
            set
            {
                this.контактField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("БанкРекв")]
        public БанкРекв[] БанкРекв
        {
            get
            {
                return this.банкРеквField;
            }
            set
            {
                this.банкРеквField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКПО
        {
            get
            {
                return this.оКПОField;
            }
            set
            {
                this.оКПОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СтруктПодр
        {
            get
            {
                return this.структПодрField;
            }
            set
            {
                this.структПодрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИнфДляУчаст
        {
            get
            {
                return this.инфДляУчастField;
            }
            set
            {
                this.инфДляУчастField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Адрес", Namespace = "", IsNullable = false)]
    public partial class АдресТип
    {

        private string кодГАРField;

        private АдрРФТип[] адрРФField;

        private АдрИнфТип[] адрИнфField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string КодГАР
        {
            get
            {
                return this.кодГАРField;
            }
            set
            {
                this.кодГАРField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдрРФТип[] АдрРФ
        {
            get
            {
                return this.адрРФField;
            }
            set
            {
                this.адрРФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрИнф", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public АдрИнфТип[] АдрИнф
        {
            get
            {
                return this.адрИнфField;
            }
            set
            {
                this.адрИнфField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип
    {

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get
            {
                return this.кодРегионField;
            }
            set
            {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get
            {
                return this.квартField;
            }
            set
            {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИнфТип
    {

        private string кодСтрField;

        private string адрТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр
        {
            get
            {
                return this.кодСтрField;
            }
            set
            {
                this.кодСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст
        {
            get
            {
                return this.адрТекстField;
            }
            set
            {
                this.адрТекстField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Контакт", Namespace = "", IsNullable = false)]
    public partial class КонтактТип
    {

        private string тлфField;

        private string элПочтаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф
        {
            get
            {
                return this.тлфField;
            }
            set
            {
                this.тлфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ЭлПочта
        {
            get
            {
                return this.элПочтаField;
            }
            set
            {
                this.элПочтаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("УчастникТип",Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public partial class БанкРекв
    {

        private БанкРеквСвБанк[] свБанкField;

        private string номерСчетаField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвБанк", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public БанкРеквСвБанк[] СвБанк
        {
            get
            {
                return this.свБанкField;
            }
            set
            {
                this.свБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчета
        {
            get
            {
                return this.номерСчетаField;
            }
            set
            {
                this.номерСчетаField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class БанкРеквСвБанк
    {

        private string наимБанкField;

        private string бИКField;

        private string корСчетField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимБанк
        {
            get
            {
                return this.наимБанкField;
            }
            set
            {
                this.наимБанкField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string БИК
        {
            get
            {
                return this.бИКField;
            }
            set
            {
                this.бИКField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КорСчет
        {
            get
            {
                return this.корСчетField;
            }
            set
            {
                this.корСчетField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ИдСвСвЮЛУч
    {

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ИдСвСвЮлНеУч
    {

        private string наимОргField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ИдСвСвИнНеУч
    {

        private string наимОргField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ТекстИнф", Namespace = "", IsNullable = false)]
    public partial class ТекстИнфТип
    {

        private string идентифField;

        private string значенField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Идентиф
        {
            get
            {
                return this.идентифField;
            }
            set
            {
                this.идентифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Значен
        {
            get
            {
                return this.значенField;
            }
            set
            {
                this.значенField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлСвУчДокОбор[] свУчДокОборField;

        private ФайлДокумент[] документField;

        private string идФайлField;

        private string версФормField;

        private string версПрогField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвУчДокОбор", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлСвУчДокОбор[] СвУчДокОбор
        {
            get
            {
                return this.свУчДокОборField;
            }
            set
            {
                this.свУчДокОборField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Документ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокумент[] Документ
        {
            get
            {
                return this.документField;
            }
            set
            {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get
            {
                return this.идФайлField;
            }
            set
            {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсФорм
        {
            get
            {
                return this.версФормField;
            }
            set
            {
                this.версФормField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвУчДокОбор
    {

        private ФайлСвУчДокОборСвОЭДОтпр[] свОЭДОтпрField;

        private string идОтпрField;

        private string идПолField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвОЭДОтпр", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлСвУчДокОборСвОЭДОтпр[] СвОЭДОтпр
        {
            get
            {
                return this.свОЭДОтпрField;
            }
            set
            {
                this.свОЭДОтпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдОтпр
        {
            get
            {
                return this.идОтпрField;
            }
            set
            {
                this.идОтпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдПол
        {
            get
            {
                return this.идПолField;
            }
            set
            {
                this.идПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвУчДокОборСвОЭДОтпр
    {

        private string наимОргField;

        private string иННЮЛField;

        private string идЭДОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЭДО
        {
            get
            {
                return this.идЭДОField;
            }
            set
            {
                this.идЭДОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументСвСчФакт[] свСчФактField;

        private ФайлДокументТаблСчФакт[] таблСчФактField;

        private ФайлДокументСвПродПер[] свПродПерField;

        private ФайлДокументПодписант[] подписантField;

        private string кНДField;

        private string функцияField;

        private string поФактХЖField;

        private string наимДокОпрField;

        private string датаИнфПрField;

        private string времИнфПрField;

        private string наимЭконСубСостField;

        private string оснДоверОргСостField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвСчФакт", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФакт[] СвСчФакт
        {
            get
            {
                return this.свСчФактField;
            }
            set
            {
                this.свСчФактField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТаблСчФакт", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументТаблСчФакт[] ТаблСчФакт
        {
            get
            {
                return this.таблСчФактField;
            }
            set
            {
                this.таблСчФактField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПродПер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПер[] СвПродПер
        {
            get
            {
                return this.свПродПерField;
            }
            set
            {
                this.свПродПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Подписант", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументПодписант[] Подписант
        {
            get
            {
                return this.подписантField;
            }
            set
            {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КНД
        {
            get
            {
                return this.кНДField;
            }
            set
            {
                this.кНДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Функция
        {
            get
            {
                return this.функцияField;
            }
            set
            {
                this.функцияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПоФактХЖ
        {
            get
            {
                return this.поФактХЖField;
            }
            set
            {
                this.поФактХЖField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДокОпр
        {
            get
            {
                return this.наимДокОпрField;
            }
            set
            {
                this.наимДокОпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИнфПр
        {
            get
            {
                return this.датаИнфПрField;
            }
            set
            {
                this.датаИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВремИнфПр
        {
            get
            {
                return this.времИнфПрField;
            }
            set
            {
                this.времИнфПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЭконСубСост
        {
            get
            {
                return this.наимЭконСубСостField;
            }
            set
            {
                this.наимЭконСубСостField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверОргСост
        {
            get
            {
                return this.оснДоверОргСостField;
            }
            set
            {
                this.оснДоверОргСостField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФакт
    {

        private ФайлДокументСвСчФактИспрСчФ[] испрСчФField;

        private УчастникТип[] свПродField;

        private ФайлДокументСвСчФактГрузОт[] грузОтField;

        private УчастникТип[] грузПолучField;

        private ФайлДокументСвСчФактСвПРД[] свПРДField;

        private УчастникТип[] свПокупField;

        private ФайлДокументСвСчФактДопСвФХЖ1[] допСвФХЖ1Field;

        private ФайлДокументСвСчФактИнфПолФХЖ1[] инфПолФХЖ1Field;

        private string номерСчФField;

        private string датаСчФField;

        private string кодОКВField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИспрСчФ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФактИспрСчФ[] ИспрСчФ
        {
            get
            {
                return this.испрСчФField;
            }
            set
            {
                this.испрСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПрод", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип[] СвПрод
        {
            get
            {
                return this.свПродField;
            }
            set
            {
                this.свПродField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузОт", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФактГрузОт[] ГрузОт
        {
            get
            {
                return this.грузОтField;
            }
            set
            {
                this.грузОтField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузПолуч", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип[] ГрузПолуч
        {
            get
            {
                return this.грузПолучField;
            }
            set
            {
                this.грузПолучField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПРД", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФактСвПРД[] СвПРД
        {
            get
            {
                return this.свПРДField;
            }
            set
            {
                this.свПРДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПокуп", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип[] СвПокуп
        {
            get
            {
                return this.свПокупField;
            }
            set
            {
                this.свПокупField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДопСвФХЖ1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФактДопСвФХЖ1[] ДопСвФХЖ1
        {
            get
            {
                return this.допСвФХЖ1Field;
            }
            set
            {
                this.допСвФХЖ1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвСчФактИнфПолФХЖ1[] ИнфПолФХЖ1
        {
            get
            {
                return this.инфПолФХЖ1Field;
            }
            set
            {
                this.инфПолФХЖ1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчФ
        {
            get
            {
                return this.номерСчФField;
            }
            set
            {
                this.номерСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСчФ
        {
            get
            {
                return this.датаСчФField;
            }
            set
            {
                this.датаСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОКВ
        {
            get
            {
                return this.кодОКВField;
            }
            set
            {
                this.кодОКВField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактИспрСчФ
    {

        private string номИспрСчФField;

        private string датаИспрСчФField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомИспрСчФ
        {
            get
            {
                return this.номИспрСчФField;
            }
            set
            {
                this.номИспрСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИспрСчФ
        {
            get
            {
                return this.датаИспрСчФField;
            }
            set
            {
                this.датаИспрСчФField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактГрузОт
    {

        private string онЖеField;

        private УчастникТип[] грузОтпрField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ОнЖе
        {
            get
            {
                return this.онЖеField;
            }
            set
            {
                this.онЖеField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузОтпр", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип[] ГрузОтпр
        {
            get
            {
                return this.грузОтпрField;
            }
            set
            {
                this.грузОтпрField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактСвПРД
    {

        private string номерПРДField;

        private string датаПРДField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерПРД
        {
            get
            {
                return this.номерПРДField;
            }
            set
            {
                this.номерПРДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПРД
        {
            get
            {
                return this.датаПРДField;
            }
            set
            {
                this.датаПРДField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактДопСвФХЖ1
    {

        private string идГосКонField;

        private string наимОКВField;

        private decimal курсВалField;

        private bool курсВалFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдГосКон
        {
            get
            {
                return this.идГосКонField;
            }
            set
            {
                this.идГосКонField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОКВ
        {
            get
            {
                return this.наимОКВField;
            }
            set
            {
                this.наимОКВField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КурсВал
        {
            get
            {
                return this.курсВалField;
            }
            set
            {
                this.курсВалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КурсВалSpecified
        {
            get
            {
                return this.курсВалFieldSpecified;
            }
            set
            {
                this.курсВалFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактИнфПолФХЖ1
    {

        private ТекстИнфТип[] текстИнфField;

        private string идФайлИнфПолField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ТекстИнфТип[] ТекстИнф
        {
            get
            {
                return this.текстИнфField;
            }
            set
            {
                this.текстИнфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол
        {
            get
            {
                return this.идФайлИнфПолField;
            }
            set
            {
                this.идФайлИнфПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФакт
    {

        private ФайлДокументТаблСчФактСведТов[] сведТовField;

        private ФайлДокументТаблСчФактВсегоОпл[] всегоОплField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведТов", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументТаблСчФактСведТов[] СведТов
        {
            get
            {
                return this.сведТовField;
            }
            set
            {
                this.сведТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ВсегоОпл", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументТаблСчФактВсегоОпл[] ВсегоОпл
        {
            get
            {
                return this.всегоОплField;
            }
            set
            {
                this.всегоОплField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактСведТов
    {

        private СумАкцизТип[] акцизField;

        private СумНДСТип[] сумНалField;

        private ФайлДокументТаблСчФактСведТовСвТД[] свТДField;

        private ТекстИнфТип[] инфПолФХЖ2Field;

        private ФайлДокументТаблСчФактСведТовДопСведТов[] допСведТовField;

        private string номСтрField;

        private string наимТовField;

        private string оКЕИ_ТовField;

        private decimal колТовField;

        private bool колТовFieldSpecified;

        private decimal ценаТовField;

        private bool ценаТовFieldSpecified;

        private decimal стТовБезНДСField;

        private bool стТовБезНДСFieldSpecified;

        private string налСтField;

        private decimal стТовУчНалField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Акциз", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СумАкцизТип[] Акциз
        {
            get
            {
                return this.акцизField;
            }
            set
            {
                this.акцизField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СумНал", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СумНДСТип[] СумНал
        {
            get
            {
                return this.сумНалField;
            }
            set
            {
                this.сумНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвТД", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументТаблСчФактСведТовСвТД[] СвТД
        {
            get
            {
                return this.свТДField;
            }
            set
            {
                this.свТДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ТекстИнфТип[] ИнфПолФХЖ2
        {
            get
            {
                return this.инфПолФХЖ2Field;
            }
            set
            {
                this.инфПолФХЖ2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДопСведТов", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументТаблСчФактСведТовДопСведТов[] ДопСведТов
        {
            get
            {
                return this.допСведТовField;
            }
            set
            {
                this.допСведТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомСтр
        {
            get
            {
                return this.номСтрField;
            }
            set
            {
                this.номСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимТов
        {
            get
            {
                return this.наимТовField;
            }
            set
            {
                this.наимТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКЕИ_Тов
        {
            get
            {
                return this.оКЕИ_ТовField;
            }
            set
            {
                this.оКЕИ_ТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТов
        {
            get
            {
                return this.колТовField;
            }
            set
            {
                this.колТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолТовSpecified
        {
            get
            {
                return this.колТовFieldSpecified;
            }
            set
            {
                this.колТовFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ЦенаТов
        {
            get
            {
                return this.ценаТовField;
            }
            set
            {
                this.ценаТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ЦенаТовSpecified
        {
            get
            {
                return this.ценаТовFieldSpecified;
            }
            set
            {
                this.ценаТовFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДС
        {
            get
            {
                return this.стТовБезНДСField;
            }
            set
            {
                this.стТовБезНДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСSpecified
        {
            get
            {
                return this.стТовБезНДСFieldSpecified;
            }
            set
            {
                this.стТовБезНДСFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НалСт
        {
            get
            {
                return this.налСтField;
            }
            set
            {
                this.налСтField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНал
        {
            get
            {
                return this.стТовУчНалField;
            }
            set
            {
                this.стТовУчНалField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактСведТовСвТД
    {

        private string кодПроисхField;

        private string номерТДField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодПроисх
        {
            get
            {
                return this.кодПроисхField;
            }
            set
            {
                this.кодПроисхField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерТД
        {
            get
            {
                return this.номерТДField;
            }
            set
            {
                this.номерТДField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактСведТовДопСведТов
    {

        private string прТовРабField;

        private string допПризнField;

        private string кодТовField;

        private string наимЕдИзмField;

        private string крНаимСтрПрField;

        private decimal надлОтпField;

        private bool надлОтпFieldSpecified;

        private string корСчДебетField;

        private string корСчКредитField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПрТовРаб
        {
            get
            {
                return this.прТовРабField;
            }
            set
            {
                this.прТовРабField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопПризн
        {
            get
            {
                return this.допПризнField;
            }
            set
            {
                this.допПризнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодТов
        {
            get
            {
                return this.кодТовField;
            }
            set
            {
                this.кодТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЕдИзм
        {
            get
            {
                return this.наимЕдИзмField;
            }
            set
            {
                this.наимЕдИзмField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КрНаимСтрПр
        {
            get
            {
                return this.крНаимСтрПрField;
            }
            set
            {
                this.крНаимСтрПрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal НадлОтп
        {
            get
            {
                return this.надлОтпField;
            }
            set
            {
                this.надлОтпField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НадлОтпSpecified
        {
            get
            {
                return this.надлОтпFieldSpecified;
            }
            set
            {
                this.надлОтпFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КорСчДебет
        {
            get
            {
                return this.корСчДебетField;
            }
            set
            {
                this.корСчДебетField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КорСчКредит
        {
            get
            {
                return this.корСчКредитField;
            }
            set
            {
                this.корСчКредитField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактВсегоОпл
    {

        private decimal неттоВсField;

        private bool неттоВсFieldSpecified;

        private СумНДСТип[] сумНалВсегоField;

        private decimal стТовБезНДСВсегоField;

        private bool стТовБезНДСВсегоFieldSpecified;

        private decimal стТовУчНалВсегоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal НеттоВс
        {
            get
            {
                return this.неттоВсField;
            }
            set
            {
                this.неттоВсField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НеттоВсSpecified
        {
            get
            {
                return this.неттоВсFieldSpecified;
            }
            set
            {
                this.неттоВсFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СумНалВсего", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СумНДСТип[] СумНалВсего
        {
            get
            {
                return this.сумНалВсегоField;
            }
            set
            {
                this.сумНалВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДСВсего
        {
            get
            {
                return this.стТовБезНДСВсегоField;
            }
            set
            {
                this.стТовБезНДСВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСВсегоSpecified
        {
            get
            {
                return this.стТовБезНДСВсегоFieldSpecified;
            }
            set
            {
                this.стТовБезНДСВсегоFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНалВсего
        {
            get
            {
                return this.стТовУчНалВсегоField;
            }
            set
            {
                this.стТовУчНалВсегоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПер
    {

        private ФайлДокументСвПродПерСвПер[] свПерField;

        private ФайлДокументСвПродПерИнфПолФХЖ3[] инфПолФХЖ3Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПер[] СвПер
        {
            get
            {
                return this.свПерField;
            }
            set
            {
                this.свПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнфПолФХЖ3", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерИнфПолФХЖ3[] ИнфПолФХЖ3
        {
            get
            {
                return this.инфПолФХЖ3Field;
            }
            set
            {
                this.инфПолФХЖ3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПер
    {

        private ФайлДокументСвПродПерСвПерОснПер[] оснПерField;

        private ФайлДокументСвПродПерСвПерСвЛицПер[] свЛицПерField;

        private ФайлДокументСвПродПерСвПерТранГруз[] транГрузField;

        private ФайлДокументСвПродПерСвПерСвПерВещи[] свПерВещиField;

        private string содОперField;

        private string видОперField;

        private string датаПерField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОснПер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерОснПер[] ОснПер
        {
            get
            {
                return this.оснПерField;
            }
            set
            {
                this.оснПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвЛицПер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПер[] СвЛицПер
        {
            get
            {
                return this.свЛицПерField;
            }
            set
            {
                this.свЛицПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТранГруз", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерТранГруз[] ТранГруз
        {
            get
            {
                return this.транГрузField;
            }
            set
            {
                this.транГрузField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПерВещи", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвПерВещи[] СвПерВещи
        {
            get
            {
                return this.свПерВещиField;
            }
            set
            {
                this.свПерВещиField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СодОпер
        {
            get
            {
                return this.содОперField;
            }
            set
            {
                this.содОперField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВидОпер
        {
            get
            {
                return this.видОперField;
            }
            set
            {
                this.видОперField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПер
        {
            get
            {
                return this.датаПерField;
            }
            set
            {
                this.датаПерField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерОснПер
    {

        private string наимОснField;

        private string номОснField;

        private string датаОснField;

        private string допСвОснField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОсн
        {
            get
            {
                return this.наимОснField;
            }
            set
            {
                this.наимОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомОсн
        {
            get
            {
                return this.номОснField;
            }
            set
            {
                this.номОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаОсн
        {
            get
            {
                return this.датаОснField;
            }
            set
            {
                this.датаОснField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДопСвОсн
        {
            get
            {
                return this.допСвОснField;
            }
            set
            {
                this.допСвОснField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПер
    {

        private ФайлДокументСвПродПерСвПерСвЛицПерРабОргПрод[] рабОргПродField;

        private ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо[] инЛицоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("РабОргПрод", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерРабОргПрод[] РабОргПрод
        {
            get
            {
                return this.рабОргПродField;
            }
            set
            {
                this.рабОргПродField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИнЛицо", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо[] ИнЛицо
        {
            get
            {
                return this.инЛицоField;
            }
            set
            {
                this.инЛицоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерРабОргПрод
    {

        private ФИОТип[] фИОField;

        private string должностьField;

        private string иныеСведField;

        private string оснПолнField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность
        {
            get
            {
                return this.должностьField;
            }
            set
            {
                this.должностьField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолн
        {
            get
            {
                return this.оснПолнField;
            }
            set
            {
                this.оснПолнField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицо
    {

        private ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоПредОргПер[] предОргПерField;

        private ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер[] фЛПерField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПредОргПер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоПредОргПер[] ПредОргПер
        {
            get
            {
                return this.предОргПерField;
            }
            set
            {
                this.предОргПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФЛПер", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер[] ФЛПер
        {
            get
            {
                return this.фЛПерField;
            }
            set
            {
                this.фЛПерField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоПредОргПер
    {

        private ФИОТип[] фИОField;

        private string должностьField;

        private string иныеСведField;

        private string наимОргПерField;

        private string оснДоверОргПерField;

        private string оснПолнПредПерField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность
        {
            get
            {
                return this.должностьField;
            }
            set
            {
                this.должностьField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОргПер
        {
            get
            {
                return this.наимОргПерField;
            }
            set
            {
                this.наимОргПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверОргПер
        {
            get
            {
                return this.оснДоверОргПерField;
            }
            set
            {
                this.оснДоверОргПерField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнПредПер
        {
            get
            {
                return this.оснПолнПредПерField;
            }
            set
            {
                this.оснПолнПредПерField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерСвЛицПерИнЛицоФЛПер
    {

        private ФИОТип[] фИОField;

        private string иныеСведField;

        private string оснДоверФЛField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснДоверФЛ
        {
            get
            {
                return this.оснДоверФЛField;
            }
            set
            {
                this.оснДоверФЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерТранГруз
    {

        private ФайлДокументСвПродПерСвПерТранГрузТранНакл[] транНаклField;

        private УчастникТип[] перевозчикField;

        private string свТранГрузField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТранНакл", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументСвПродПерСвПерТранГрузТранНакл[] ТранНакл
        {
            get
            {
                return this.транНаклField;
            }
            set
            {
                this.транНаклField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Перевозчик", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public УчастникТип[] Перевозчик
        {
            get
            {
                return this.перевозчикField;
            }
            set
            {
                this.перевозчикField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвТранГруз
        {
            get
            {
                return this.свТранГрузField;
            }
            set
            {
                this.свТранГрузField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерТранГрузТранНакл
    {

        private string номТранНаклField;

        private string датаТранНаклField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомТранНакл
        {
            get
            {
                return this.номТранНаклField;
            }
            set
            {
                this.номТранНаклField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаТранНакл
        {
            get
            {
                return this.датаТранНаклField;
            }
            set
            {
                this.датаТранНаклField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерСвПерСвПерВещи
    {

        private string датаПерВещField;

        private string свПерВещField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПерВещ
        {
            get
            {
                return this.датаПерВещField;
            }
            set
            {
                this.датаПерВещField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвПерВещ
        {
            get
            {
                return this.свПерВещField;
            }
            set
            {
                this.свПерВещField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвПродПерИнфПолФХЖ3
    {

        private ТекстИнфТип[] текстИнфField;

        private string идФайлИнфПолField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф")]
        public ТекстИнфТип[] ТекстИнф
        {
            get
            {
                return this.текстИнфField;
            }
            set
            {
                this.текстИнфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол
        {
            get
            {
                return this.идФайлИнфПолField;
            }
            set
            {
                this.идФайлИнфПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private ФайлДокументПодписантФЛ[] флField;

        private СвИПТип[] ипField;

        private ФайлДокументПодписантЮЛ[] юлField;

        private string облПолнField;

        private string статусField;

        private string оснПолнField;

        private string оснПолнОргField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФЛ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументПодписантФЛ[] ФЛ
        {
            get
            {
                return this.флField;
            }
            set
            {
                this.флField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИП", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public СвИПТип[] ИП
        {
            get
            {
                return this.ипField;
            }
            set
            {
                this.ипField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ФайлДокументПодписантЮЛ[] ЮЛ
        {
            get
            {
                return this.юлField;
            }
            set
            {
                this.юлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОблПолн
        {
            get
            {
                return this.облПолнField;
            }
            set
            {
                this.облПолнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Статус
        {
            get
            {
                return this.статусField;
            }
            set
            {
                this.статусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолн
        {
            get
            {
                return this.оснПолнField;
            }
            set
            {
                this.оснПолнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОснПолнОрг
        {
            get
            {
                return this.оснПолнОргField;
            }
            set
            {
                this.оснПолнОргField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантФЛ
    {

        private ФИОТип[] фИОField;

        private string госРегИПВыдДовField;

        private string иННФЛField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ГосРегИПВыдДов
        {
            get
            {
                return this.госРегИПВыдДовField;
            }
            set
            {
                this.госРегИПВыдДовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантЮЛ
    {

        private ФИОТип[] фИОField;

        private string госРегИПВыдДовField;

        private string иННЮЛField;

        private string наимОргField;

        private string должнField;

        private string иныеСведField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ФИОТип[] ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ГосРегИПВыдДов
        {
            get
            {
                return this.госРегИПВыдДовField;
            }
            set
            {
                this.госРегИПВыдДовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должн
        {
            get
            {
                return this.должнField;
            }
            set
            {
                this.должнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИныеСвед
        {
            get
            {
                return this.иныеСведField;
            }
            set
            {
                this.иныеСведField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Адрес", typeof(АдресТип))]
        [System.Xml.Serialization.XmlElementAttribute("БанкРекв", typeof(БанкРекв))]
        [System.Xml.Serialization.XmlElementAttribute("ИдСв", typeof(ИдСв))]
        [System.Xml.Serialization.XmlElementAttribute("Контакт", typeof(КонтактТип))]
        [System.Xml.Serialization.XmlElementAttribute("ТекстИнф", typeof(ТекстИнфТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФИО", typeof(ФИОТип))]
        [System.Xml.Serialization.XmlElementAttribute("Файл", typeof(Файл))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
